pipeline {
    environment {
        DEFAULT_SUBJECT = 'Health Check: $BUILD_STATUS'
    }
    agent {
        label params.Environments
    }    
    stages {
        stage('Cleanup Workspace') {
            steps {
                cleanWs()
                echo "Cleaned Up Workspace For Project"
                sh "docker rm --force petclinic"
            }
        }
        stage('Docker Pull') {
            steps {
      	        withCredentials([usernamePassword(credentialsId: 'dockerHub', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
        	    sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
                sh "docker pull oleksandriyskiy/petclinic:${params.Tag}"}
                }
        }
        stage('Docker logout') {
            steps {    
      	        sh "docker logout"
                }
            }   
        stage('Deploy') {
            steps {
                sh "docker run -dp 8080:8080 --name petclinic oleksandriyskiy/petclinic:${params.Tag}"
            }
        }
        stage('Healthcheck') {
            steps {
                sh "/home/jenkins/healthcheck.sh"
            }
        }
    }
    post{
        always{
            emailext to: "olekskloch@gmail.com",
            subject: "${JOB_NAME} pipeline",
            body: "The ${JOB_NAME} build number ${BUILD_ID} is ${DEFAULT_SUBJECT}",
            attachLog: true
        }
    }
    
}