pipeline { 
    agent {
        node {
            label 'linux_node'
        }
    }
    stages { 
        stage('Check status') {
            steps {
                sh "echo 'Pipeline for ${BRANCH_NAME} branch'"
            }
        }
        stage('Cleanup Workspace') {
            steps {
                cleanWs()
                echo "Cleaned Up Workspace For Project"
            }
        }
        stage('Code Checkout') {
            steps {
                checkout scmGit(
                    branches: [[name: "*/${BRANCH_NAME}"]], 
                    extensions: [], 
                    userRemoteConfigs: [[credentialsId: 'petclinic', url: 'git@git.epam.com:oleksandr_klochko/multibrunch_spring-petclinic.git']])
            }
        }
        stage('Check commit message') {
            steps {
                sh "chmod +x ./message_check.sh"
                sh "./message_check.sh"
            }
        }
        stage('Lint Dockerfile') {
            steps {
                sh "hadolint Dockerfile | tee -a hadolint_report.txt"
            }
            post {
                always {
                    archiveArtifacts "hadolint_report.txt"
                }
            }
        }
    }
}


