pipeline { 
    agent {
        node {
            label 'linux_node'
            customWorkspace '/home/jenkins/jenkins_node/springboot3_job'
        }
    }
    stages { 
        stage('Check status') {
            steps {
                sh "echo 'Pipeline for springboot3 branch'"
            }
        }
        stage('Cleanup Workspace') {
            steps {
                cleanWs()
                echo 'Cleaned Up Workspace For Project'
            }
        }
        stage('Code Checkout') {
            steps {
                checkout scmGit(
                    branches: [[name: '*/feature']], 
                    extensions: [], 
                    userRemoteConfigs: [[credentialsId: 'petclinic', url: 'git@git.epam.com:oleksandr_klochko/multibrunch_spring-petclinic.git']])
            }
        }
        stage('Check commit message') {
            steps {
                sh '/home/jenkins/jenkins_node/message_check.sh'
            }
        }
        stage('Lint Dockerfile') {
            steps {
                sh 'hadolint Dockerfile | tee -a hadolint_report.txt'
            }
            post {
                always {
                    archiveArtifacts 'hadolint_report.txt'
                }
            }
        }
    }
}


