apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: db
data:
  database_name: crud
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: db
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS crud;
    USE crud;
    CREATE TABLE task(
      id INT(11) PRIMARY KEY AUTO_INCREMENT,
      title VARCHAR(255) NOT NULL,
      description TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    DESCRIBE task;