apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv1
  namespace: db
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0802626d6428a9c2d
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc1
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0802626d6428a9c2d
  directoryPerms: "777"