# Better to use this storage class in case one availability zone
# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: ebs
# provisioner: kubernetes.io/aws-ebs
# volumeBindingMode: WaitForFirstConsumer
# parameters:
#   type: gp2
#   fsType: "ext4"
# allowedTopologies:
# - matchLabelExpressions:
#   - key: failure-domain.beta.kubernetes.io/zone
#     values:
#     - eu-central-1b
#     - eu-central-1c